#!/bin/sh

set -e

# needs 6.5GB free diskspace for building
# TODO:
#       - allow single deb to be injected

export LC_ALL=C

SUITE="trusty"
ARCH="armhf"

NOW=$(date +%Y%m%d)
OUTDIR="./out-$NOW"
TAILPID=
KEEP=
DO_PPA=

PREINSTALLED="true"
IMAGEFORMAT="plain"
PROJECT="ubuntu-touch"

[ ! $(which qemu-debootstrap) ] && echo "please install the qemu-user-static package" && exit 1

cleanup()
{
	[ -n "$TAILPID" ] && kill -9 $TAILPID
	if [ -e "$CHROOT" ]; then
		umount $CHROOT/sys >/dev/null 2>&1 || true
		umount $CHROOT/proc >/dev/null 2>&1 || true
		if [ -e "$CHROOT/build.log" ]; then
			LOG=./build-$NOW-$ARCH.log
			[ -e "$OUTDIR" ] && LOG=$OUTDIR/build-$NOW-$ARCH.log
			cp $CHROOT/build.log $LOG
		fi
		[ -z "$KEEP" ] && rm -rf $CHROOT >/dev/null 2>&1 || true
	fi
}

trap cleanup 0 1 2 3 9 15

usage()
{
	echo "usage: $(basename $0)\n
	-h|--help		this page
	-a|--arch (i386|armhf)	pick an arch, default: armhf
	-m|--mirror (url)	url to local mirror
	-o|--outdir (dir)	output dir, default: ./out-\$timestamp
	-k|--keep-chroot	keep the build environment around for inspection
	-p|--ppa (ppa url)	a ppa url in the form of ppa:user/ppaname\n"
#	-i|--inject-package (path to deb)	inject a single .deb in the build
	exit 1
}

SUDOARGS="$@"

while [ $# -gt 0 ]; do
	case "$1" in
		-h|--help)
			usage
			;;
		-a|--arch)
			[ -n "$2" ] && ARCH=$2 shift || usage
			;;
		-m|--mirror)
			[ -n "$2" ] && MIRROR=$2 shift || usage
			;;
		-o|--outdir)
			[ -n "$2" ] && OUTDIR=$2 shift || usage
			;;
		-k|--keep-chroot)
			KEEP=1
			;;
		-p|--ppa)
			[ -n "$2" ] && PPAOPT=$2 shift || usage
			MYPPA=$(echo $PPAOPT|sed 's/^.*://')
			PPA_USER=${MYPPA%%/*}
			PPA_NAME=${MYPPA##*/}
			DO_PPA=1
			;;
		*)
			usage
			;;
	esac
	shift
done

case $ARCH in
	i386)
		MIRROR="${MIRROR:-http://archive.ubuntu.com/ubuntu}"
		BOOTSTRAP_BIN="debootstrap --arch i386"
		LB_BOOTSTRAP_QEMU_ARCHITECTURES=""
		LB_BOOTSTRAP_QEMU_STATIC=""
		;;
	armhf)
		MIRROR="${MIRROR:-http://ports.ubuntu.com/ubuntu-ports}"
		BOOTSTRAP_BIN="qemu-debootstrap --arch armhf"
		LB_BOOTSTRAP_QEMU_ARCHITECTURES="armhf"
		LB_BOOTSTRAP_QEMU_STATIC="/usr/bin/qemu-arm-static"
		;;
	*)
		usage
		;;
esac

BUILDOPTS="PREINSTALLED=${PREINSTALLED} \
	LB_BOOTSTRAP_QEMU_ARCHITECTURES=${LB_BOOTSTRAP_QEMU_ARCHITECTURES} \
	LB_BOOTSTRAP_QEMU_STATIC=${LB_BOOTSTRAP_QEMU_STATIC} \
	IMAGEFORMAT=${IMAGEFORMAT} \
	MIRROR=${MIRROR} \
	NOW=${NOW} \
	SUITE=${SUITE} \
	PROJECT=${PROJECT} \
	ARCH=${ARCH}"

[ $(id -u) -ne 0 ] && exec sudo $0 $SUDOARGS

CHROOT=$(mktemp -d /tmp/rootstock.XXXXX)

touch $CHROOT/build.log
tail -f $CHROOT/build.log &
TAILPID=$!

exec 3>&1 4>&2 >$CHROOT/build.log 2>&1

do_chroot()
{
	ROOT="$1"
	CMD="$2"
	chroot $ROOT mount -t proc proc /proc
	chroot $ROOT mount -t sysfs sys /sys
	chroot $ROOT $CMD
	chroot $ROOT umount /sys
	chroot $ROOT umount /proc
}

set_up_ppa()
{
	PPA_API="https://launchpad.net/api/1.0/~$PPA_USER/+archive/$PPA_NAME"
	PPA_FINGERPRINT="$(wget -O- -q $PPA_API|tr ',' '\n'|\
		grep signing_key_fingerprint|\
		sed s/\"//g|tail -c9)"
	KEY_URL="http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x$PPA_FINGERPRINT"
	KEY=$(wget -O- -q $KEY_URL|sed -e '/-----/,$!d'|sed '/^<.*/d')
	PPA_CONFDIR="$CHROOT/usr/share/livecd-rootfs/live-build/ubuntu-touch/archives"
	mkdir -p "$PPA_CONFDIR"
	echo "$KEY" >"$PPA_CONFDIR/$PPA_USER-$PPA_NAME.key.chroot"
	PPA_SOURCESLIST="deb http://ppa.launchpad.net/$PPA_USER/$PPA_NAME/ubuntu $SUITE main"
	echo "$PPA_SOURCESLIST" >"$PPA_CONFDIR/$PPA_USER-$PPA_NAME.list.chroot"
}

build_chroot()
{
	$BOOTSTRAP_BIN $SUITE $CHROOT $MIRROR
	echo "deb $MIRROR $SUITE main universe" >$CHROOT/etc/apt/sources.list
	do_chroot $CHROOT "apt-get -y update"
	do_chroot $CHROOT "apt-get -y install livecd-rootfs"
	mkdir -p $CHROOT/build
	chroot $CHROOT sh -c "cd /build && rm -rf auto && mkdir -p auto && \
		for f in config build clean; do ln -s /usr/share/livecd-rootfs/live-build/auto/\$f auto/; done"
	# hack for click package location
	sed -i 's,archive-team.internal,people.canonical.com/~ubuntu-archive,' \
		$CHROOT/usr/share/livecd-rootfs/live-build/ubuntu-touch/hooks/60-install-click.chroot
}

build_touch()
{
	chroot $CHROOT sh -c "cd /build && lb clean --purge"
	chroot $CHROOT sh -c "cd /build && $BUILDOPTS lb config"
	chroot $CHROOT sh -c "cd /build && $BUILDOPTS lb build"
}

copy_artefacts()
{
	mkdir -p $OUTDIR
	for file in $(ls $CHROOT/build/livecd.*|grep -v bootimg); do
		cp $file $OUTDIR/$(echo $file|sed -e s/^.*livecd.// -e s/rootfs/rootfs-$ARCH/)
	done
}

build_chroot
[ -n "$DO_PPA" ] && set_up_ppa
build_touch
copy_artefacts
