#!/bin/sh
#
# Dump the HEAD commit for every repository tracked by repo
#

set -e

repo list | awk -F' ' '{print $1}' | while read project; do
    gitlog=`git --git-dir=$PWD/$project/.git log -n 1 --pretty="format:%h : %s"`
    echo "$project : $gitlog"
done
